version: 0.2

env:
  variables:
    APP_VERSION: v2.0.0
    REPOSITORY_URI: 061039760516.dkr.ecr.ap-south-1.amazonaws.com/better-wellness-repo
    DOCKER_CONTAINER_NAME: better-wellness-repo
    CLUSTER_NAME: sliit-better-wellness-cluster
    REGION: ap-south-1

phases:
  pre_build:
    commands:
      - echo "Setting up pre-build phase..."
      - echo "Cleaning and building the app (without tests)..."
      - mvn clean install -DskipTests
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - IMAGE_TAG=better-wellness-user-api-$APP_VERSION
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI

  post_build:
    commands:
      - echo "Post-build phase started..."
      - echo "Pushing Docker images to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo "Writing image definitions file for ECS/K8s..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "imagedefinitions.json created:"
      - cat imagedefinitions.json

      # CD: Kubernetes Deployment
      - echo "Installing kubectl manually for Amazon Linux 2023..."
      - curl -Lo kubectl https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "✅ kubectl installed to /usr/local/bin/"
      - kubectl version --client

      - echo "Updating kubeconfig to interact with EKS cluster..."
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

      - echo "Updating kubeconfig..."
      - mkdir -p ~/.kube
      - aws eks update-kubeconfig --region ap-south-1 --name sliit-better-wellness-cluster --kubeconfig ~/.kube/config
      - cat ~/.kube/config
      - kubectl get nodes || echo "⚠️ Could not connect to EKS"

      - echo "Cloning deployment manifest repo..."
      - git clone https://github.com/sliit-app-innovator/better-wellness-sre-artifact.git
      - cd better-wellness-sre-artifact/scripts

      - echo "Deploying user service..."
      - chmod +x deploy-user-service.sh
      - ./deploy-user-service.sh

artifacts:
  files:
    - target/better-wellness-user-api-1.0.0.jar
    - imagedefinitions.json
