version: 0.2

env:
  variables:
    APP_VERSION: v2.0.0
    REPOSITORY_URI: 575453794606.dkr.ecr.ap-south-1.amazonaws.com/better-wellness-repo
    DOCKER_CONTAINER_NAME: better-wellness-repo
    CLUSTER_NAME: sliit-better-wellness-cluster
    REGION: ap-south-1

phases:
  pre_build:
    commands:
      - echo "Setting up pre-build phase..."
      - echo "Cleaning and building the app (without tests)..."
      - mvn clean install -DskipTests
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - IMAGE_TAG=better-wellness-user-api-$APP_VERSION
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI

  post_build:
    commands:
      - echo "Post-build phase started..."
      - echo "Pushing Docker images to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI

      - echo "Writing image definitions file for ECS/K8s..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "imagedefinitions.json created:"
      - cat imagedefinitions.json

      # CD: Kubernetes Deployment

artifacts:
  files:
    - target/better-wellness-user-api-1.0.0.jar
    - imagedefinitions.json
